### ISSUE TITLE
RuntimeError: index out of range

### ISSUE THREAD

**Issue by mikiihuang** [AnubhavGupta3377/Text-Classification-Models#3]
Hi, when i run the train.py in the folder "textCNN model",there is an error that I cant find out what's wrong. Can you help me ? Thank you very much

```
Loaded 96000 training examples
Loaded 7600 test examples
Loaded 24000 validation examples
Epoch: 0
Traceback (most recent call last):
  File "/Users/y/Documents/Code/Text-Classification-Models-Pytorch-master/Model_TextCNN/train.py", line 43, in <module>
    train_loss,val_accuracy = model.run_epoch(dataset.train_iterator, dataset.val_iterator, i)
  File "/Users/y/Documents/Code/Text-Classification-Models-Pytorch-master/Model_TextCNN/model.py", line 85, in run_epoch
    y_pred = self.__call__(x)
  File "/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/y/Documents/Code/Text-Classification-Models-Pytorch-master/Model_TextCNN/model.py", line 45, in forward
    embedded_sent = self.embeddings(x).permute(1,2,0)
  File "/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_3.6/conda/conda-bld/pytorch_1544137972173/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:191

Process finished with exit code 1

```

**Comment by mikiihuang** [comment]
I find the answer. That's because my vocab_size is smaller than the real size. Sorry to disturb you.Thank you for the code you have shared. 👍
